version: '3'
services:
  jupyter:
      build: .
      depends_on:
      - mongodb
      volumes:
        - .:/usr/src/workspace
      ports:
      - 8888:8888
      command: jupyter notebook --allow-root --ip 0.0.0.0 
  
  mongodb:
    image: mongo:4.2.3-bionic
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=my-user # Insert your database user name
      - MONGO_INITDB_ROOT_PASSWORD=my-password # Insert your database password
    
  mongodbsetup:
    image: mongo:4.2.3-bionic
    depends_on:
      - mongodb
    volumes:
      - .:/root
    restart: "no"
    working_dir: /root/src
    command: sh load_mongo_data.sh 
